In [2]:
library(data.table)
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:data.table’:

    between, first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [12]:
hash = fread("/rds/project/rds-SDzz0CATGms/users/bt392/04_rabbit_scATAC/data/arrayexpress/hash.txt", header=F)
file = fread("/rds/project/rds-SDzz0CATGms/users/bt392/04_rabbit_scATAC/data/arrayexpress/sdrf.tsv", header=T) %>%
    setnames('Array Data File', 'file') %>% setnames('Source Name', 'sample')

In [13]:
head(hash)
head(file)

  V1                               V2
1 490f4966220e2e1cd4d91bff7c5fafd1 SLX18911_SINAA3_S1_L001_I1_001.fastq.gz
2 5e00df19d4e9356feb2ad6b6212b84c3 SLX18911_SINAA3_S1_L001_R1_001.fastq.gz
3 91811ffd7f047fd0aa60b3db3531e367 SLX18911_SINAA3_S1_L001_R2_001.fastq.gz
4 33eef2344fa00e46807b4bdf07b0bdaf SLX18911_SINAA3_S1_L001_R3_001.fastq.gz
5 98dcf8241d7e8753fdd431f7ea64b6b4 SLX18911_SINAA3_S1_L002_I1_001.fastq.gz
6 796640e8de0dfa4469be050f0286b54d SLX18911_SINAA3_S1_L002_R1_001.fastq.gz

  sample Characteristics[organism] Characteristics[organism part]
1 BGRGP1 Oryctolagus cuniculus     whole organism
2 BGRGP1 Oryctolagus cuniculus     whole organism
3 BGRGP1 Oryctolagus cuniculus     whole organism
4 BGRGP1 Oryctolagus cuniculus     whole organism
5 BGRGP1 Oryctolagus cuniculus     whole organism
6 BGRGP1 Oryctolagus cuniculus     whole organism
  Characteristics[developmental stage] Characteristics[genotype] Material Type
1 gestational day 7                    wild type genotype        DNA
2 gestational day 7                    wild type genotype        DNA
3 gestational day 7                    wild type genotype        DNA
4 gestational day 7                    wild type genotype        DNA
5 gestational day 7                    wild type genotype        DNA
6 gestational day 7                    wild type genotype        DNA
  Extract Name Comment[LIBRARY_SOURCE] Comment[LIBRARY_STRATEGY]
1 BGRGP1       GENOMIC SINGLE CELL     ATAC-seq
2 BGRGP1       GENOMIC SINGLE CELL     ATAC-seq
3 BGRGP1       GENOMIC SINGLE CELL     ATAC-seq
4 BGRGP1       GENOMIC SINGLE CELL     ATAC-seq
5 BGRGP1       GENOMIC SINGLE CELL     ATAC-seq
6 BGRGP1       GENOMIC SINGLE CELL     ATAC-seq
  Comment[cdna read] ⋯ Comment[spike in] Comment[umi barcode offset]
1 read1              ⋯ none              0
2 read1              ⋯ none              0
3 read1              ⋯ none              0
4 read1              ⋯ none              0
5 read1              ⋯ none              0
6 read1              ⋯ none              0
  Comment[umi barcode read] Comment[umi barcode size] Assay Name
1 read2                     10                        BGRGP1
2 read2                     10                        BGRGP1
3 read2                     10                        BGRGP1
4 read2                     10                        BGRGP1
5 read2                     10                        BGRGP1
6 read2                     10                        BGRGP1
  Technology Type  file
1 sequencing assay SLX18911_SINAA3_S3_L002_R1_001.fastq.gz
2 sequencing assay SLX19158_SINAA3_S13_L001_R1_001.fastq.gz
3 sequencing assay SLX18911_SINAA3_S2_L001_R2_001.fastq.gz
4 sequencing assay SLX19158_SINAA3_S16_L001_R1_001.fastq.gz
5 sequencing assay SLX18911_SINAA3_S4_L002_R2_001.fastq.gz
6 sequencing assay SLX19158_SINAA3_S13_L002_R3_001.fastq.gz
  Comment[MD5]                     Factor Value[developmental stage]
1 fc3e2cf29369ccf8ed6e78481570d1e3 gestational day 7
2 6218b464df168753e61205d6ec920b28 gestational day 7
3 322977665d0230e8083c5586e8fdaa22 gestational day 7
4 3218f2b984d45cde1da1b752e87a45aa gestational day 7
5 d7301acec2a81b332a682497979822cc gestational day 7
6 70cf02ee457a1f851097f7be80046b8f gestational day 7
  Factor Value[single cell identifier]
1 NA
2 NA
3 NA
4 NA
5 NA
6 NA

In [14]:
file$batch = sapply(strsplit(file$file, '_'), '[', 2)

In [15]:
table(file$sample, file$batch)
# All fastq's assigned to the right sample, but one file missing for BGRGP3

         SINAA3 SINAB1 SINAB3 SINAC1 SINAC3 SINAD1 SINAD3 SINAE3 SINAF3 SINAG3
  BGRGP1     64      0      0      0      0      0      0      0      0      0
  BGRGP2      0     32     64      0      0      0      0      0      0      0
  BGRGP3      0      0      0     31     64      0      0      0      0      0
  BGRGP4      0      0      0      0      0     32     64      0      0      0
  BGRGP5      0      0      0      0      0      0      0     64      0      0
  BGRGP6      0      0      0      0      0      0      0      0     64      0
  BGRGP7      0      0      0      0      0      0      0      0      0     64
  BGRGP8      0      0      0      0      0      0      0      0      0      0

         SINAH3
  BGRGP1      0
  BGRGP2      0
  BGRGP3      0
  BGRGP4      0
  BGRGP5      0
  BGRGP6      0
  BGRGP7      0
  BGRGP8     64

In [16]:
missing = hash[!hash$V2 %in% file$file]
missing

  V1                               V2
1 ece83a51f4aad746d7486c8229f10e12 SLX19158_SINAC1_S7_L001_I1_001.fastq.gz

### Updated

In [18]:
file = fread("/rds/project/rds-SDzz0CATGms/users/bt392/04_rabbit_scATAC/data/arrayexpress/sdrf_2.tsv", header=T) %>%
    setnames('Array Data File', 'file') %>% setnames('Source Name', 'sample')
file$batch = sapply(strsplit(file$file, '_'), '[', 2)
table(file$sample, file$batch)
missing = hash[!hash$V2 %in% file$file]
missing

         SINAA3 SINAB1 SINAB3 SINAC1 SINAC3 SINAD1 SINAD3 SINAE3 SINAF3 SINAG3
  BGRGP1     64      0      0      0      0      0      0      0      0      0
  BGRGP2      0     32     64      0      0      0      0      0      0      0
  BGRGP3      0      0      0     32     64      0      0      0      0      0
  BGRGP4      0      0      0      0      0     32     64      0      0      0
  BGRGP5      0      0      0      0      0      0      0     64      0      0
  BGRGP6      0      0      0      0      0      0      0      0     64      0
  BGRGP7      0      0      0      0      0      0      0      0      0     64
  BGRGP8      0      0      0      0      0      0      0      0      0      0

         SINAH3
  BGRGP1      0
  BGRGP2      0
  BGRGP3      0
  BGRGP4      0
  BGRGP5      0
  BGRGP6      0
  BGRGP7      0
  BGRGP8     64

     V1 V2