In [2]:
%matplotlib inline

In [3]:
import crested
import numpy as np
import pandas as pd
import anndata as ad

2025-03-21 14:04:09.517985: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1742565849.532497  295635 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742565849.537171  295635 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1742565849.550960  295635 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1742565849.550974  295635 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1742565849.550976  295635 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1742565849.550977  295635 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-03-21 14:04:09.555182: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [4]:
import tensorflow as tf

# Check GPU availability
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))

# Check TensorFlow build info
print(tf.sysconfig.get_build_info())

# Check CUDA version
print(tf.test.is_built_with_cuda())

# Check cuDNN version
print(tf.test.is_built_with_gpu_support())

Num GPUs Available: 1
OrderedDict([('cpu_compiler', '/usr/lib/llvm-18/bin/clang'), ('cuda_compute_capabilities', ['sm_60', 'sm_70', 'sm_80', 'sm_89', 'compute_90']), ('cuda_version', '12.5.1'), ('cudnn_version', '9'), ('is_cuda_build', True), ('is_rocm_build', False), ('is_tensorrt_build', False)])
True
True

In [5]:
data_dir = '/rds/project/rds-SDzz0CATGms/users/bt392/15_Kat_Atlas/results/data/'

In [6]:
import scipy.io

# Load the sparse matrix from the Matrix Market format
matrix = scipy.io.mmread(data_dir + "CITE_eRNA_pseudobulked.mtx")

In [7]:
matrix

<COOrdinate sparse matrix of dtype 'float64'
	with 1359474 stored elements and shape (73316, 49)>

In [8]:
adata = ad.AnnData(matrix.T.toarray())

In [9]:
meta = pd.read_csv(data_dir + "meta_pseudobulk.csv")

In [10]:
meta.index = meta['celltype']

In [11]:
peaks = pd.read_csv(data_dir + "peaks_filted.csv")

In [12]:
peaks.index = peaks['peak']

In [13]:
peaks = peaks[['chr', 'start', 'end']]

In [14]:
adata.obs = meta

In [15]:
adata.var = peaks

In [16]:
adata

AnnData object with n_obs × n_vars = 49 × 73316
    obs: 'celltype'
    var: 'chr', 'start', 'end'

In [17]:
crested.pp.train_val_test_split(
    adata,
    strategy="region",
    val_size=0.1,
    test_size=0.1,
    shuffle=True,
    random_state=42,
)

In [18]:
print(adata.var["split"].value_counts())
adata.var

split
train    58652
val       7332
test      7332
Name: count, dtype: int64

                         chr     start       end  split
peak
chr1:4699342-4699722    chr1   4699342   4699722  train
chr1:4705129-4705433    chr1   4705129   4705433  train
chr1:4714121-4714574    chr1   4714121   4714574  train
chr1:4729397-4729734    chr1   4729397   4729734  train
chr1:4731628-4731950    chr1   4731628   4731950    val
...                      ...       ...       ...    ...
chrY:90797302-90798030  chrY  90797302  90798030  train
chrY:90798311-90799235  chrY  90798311  90799235  train
chrY:90799252-90799852  chrY  90799252  90799852  train
chrY:90817784-90818297  chrY  90817784  90818297  train
chrY:90822310-90823194  chrY  90822310  90823194  train

[73316 rows x 4 columns]

In [32]:
crested.pp.change_regions_width(
    adata, 2114
)  # change the adata width of the regions to 2114bp

2025-03-21T13:41:52.235684+0000 WARNING Chromsizes file not provided. Will not check if regions are within chromosomes

In [33]:
#crested.pp.normalize_peaks(adata)

In [35]:
# %matplotlib inline
# crested.pl.bar.normalization_weights(adata, title="Normalization Weights per Cell Type")

In [36]:
# This one is a bit extreme, so either something should change with the inputs or just no normalisation

In [37]:
# Set the genome
genome = crested.Genome(
    "/home/bt392/rds/rds-bg200-hphi-gottgens/references/10x/refdata-cellranger-arc-mm10-2020-A-2.0.0/fasta/genome.fa", 
    "/home/bt392/rds/rds-bg200-hphi-gottgens/users/bt392/10_Eomes_invitro_gut/results/atac/chrombpnet/mm10.chrom.sizes"
)
crested.register_genome(
    genome
)  # Register the genome so that it can be used by the package

2025-03-21T13:42:07.354133+0000 INFO Genome genome registered.

In [38]:
datamodule = crested.tl.data.AnnDataModule(
    adata,
    batch_size=256,  # lower this if you encounter OOM errors
    max_stochastic_shift=3,  # optional data augmentation to slightly reduce overfitting
    always_reverse_complement=True,  # default True. Will double the effective size of the training dataset.
)

In [39]:
crested.tl.zoo.chrombpnet

<function crested.tl.zoo._chrombpnet.chrombpnet(seq_len: int, num_classes: int, first_conv_filters: int = 512, first_conv_filter_size: int = 5, first_conv_pool_size: int = 0, first_conv_activation: str = 'gelu', first_conv_l2: float = 1e-05, first_conv_dropout: float = 0.1, n_dil_layers: int = 8, num_filters: int = 512, filter_size: int = 3, activation: str = 'relu', output_activation: str = 'softplus', l2: float = 1e-05, dropout: float = 0.1, batch_norm: bool = True, dense_bias: bool = True) -> keras.src.models.model.Model>

In [40]:
# Load chrombpnet architecture for a dataset with 2114bp regions 

# Their default model is slightly different from the original bpnet
# mainly the width of the first convolutional filter is way smaller
model_architecture = crested.tl.zoo.chrombpnet(seq_len=2114, num_classes=49)

I0000 00:00:1742564531.028364  292489 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 79077 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-80GB, pci bus id: 0000:41:00.0, compute capability: 8.0

In [41]:
# Load the default configuration for training a topic classication model
from crested.tl import default_configs, TaskConfig

config = default_configs("peak_regression")
print(config)

# If you want to change some small parameters to an existing config, you can do it like this
# For example, the default learning rate is 0.001, but you can change it to 0.0001
# config.optimizer.learning_rate = 0.0001

TaskConfig(optimizer=<keras.src.optimizers.adam.Adam object at 0x15374c391710>, loss=<crested.tl.losses._cosinemse_log.CosineMSELogLoss object at 0x15374ddebcd0>, metrics=[<MeanAbsoluteError name=mean_absolute_error>, <MeanSquaredError name=mean_squared_error>, <CosineSimilarity name=cosine_similarity>, <PearsonCorrelation name=pearson_correlation>, <ConcordanceCorrelationCoefficient name=concordance_correlation_coefficient>, <PearsonCorrelationLog name=pearson_correlation_log>, <ZeroPenaltyMetric name=zero_penalty_metric>])

In [42]:
# setup the trainer
trainer = crested.tl.Crested(
    data=datamodule,
    model=model_architecture,
    config=config,
    project_name="/rds/project/rds-SDzz0CATGms/users/bt392/15_Kat_Atlas/results/crested",  # change to your liking
    run_name="trial1",  # change to your liking
    logger=None,  # or 'wandb', 'tensorboard'
)

2025-03-21T13:42:14.195037+0000 WARNING Output directory /rds/project/rds-SDzz0CATGms/users/bt392/15_Kat_Atlas/results/crested/trial1/checkpoints already exists. Will continue training from epoch 3.
2025-03-21T13:42:14.195441+0000 WARNING Loading a model with compile=True. The CREsted config object will be ignored.

In [ ]:
# train the model
trainer.fit(epochs=25)

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ sequence            │ (None, 2114, 4)   │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d (Conv1D)     │ (None, 2114, 512) │     10,240 │ sequence[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 2114, 512) │      2,048 │ conv1d[0][0]      │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation          │ (None, 2114, 512) │          0 │ batch_normalizat… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 2114, 512) │          0 │ activation[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_1conv         │ (None, 2110, 512) │    786,432 │ dropout[0][0]     │
│ (Conv1D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_1bn           │ (None, 2110, 512) │      2,048 │ bpnet_1conv[0][0] │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_1activation   │ (None, 2110, 512) │          0 │ bpnet_1bn[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_1crop         │ (None, 2110, 512) │          0 │ dropout[0][0]     │
│ (Cropping1D)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 2110, 512) │          0 │ bpnet_1activatio… │
│                     │                   │            │ bpnet_1crop[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_1dropout      │ (None, 2110, 512) │          0 │ add[0][0]         │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_2conv         │ (None, 2102, 512) │    786,432 │ bpnet_1dropout[0… │
│ (Conv1D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_2bn           │ (None, 2102, 512) │      2,048 │ bpnet_2conv[0][0] │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_2activation   │ (None, 2102, 512) │          0 │ bpnet_2bn[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_2crop         │ (None, 2102, 512) │          0 │ bpnet_1dropout[0… │
│ (Cropping1D)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_1 (Add)         │ (None, 2102, 512) │          0 │ bpnet_2activatio… │
│                     │                   │            │ bpnet_2crop[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_2dropout      │ (None, 2102, 512) │          0 │ add_1[0][0]       │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_3conv         │ (None, 2086, 512) │    786,432 │ bpnet_2dropout[0… │
│ (Conv1D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_3bn           │ (None, 2086, 512) │      2,048 │ bpnet_3conv[0][0] │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_3activation   │ (None, 2086, 512) │          0 │ bpnet_3bn[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_3crop         │ (None, 2086, 512) │          0 │ bpnet_2dropout[0… │
│ (Cropping1D)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_2 (Add)         │ (None, 2086, 512) │          0 │ bpnet_3activatio… │
│                     │                   │            │ bpnet_3crop[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_3dropout      │ (None, 2086, 512) │          0 │ add_2[0][0]       │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_4conv         │ (None, 2054, 512) │    786,432 │ bpnet_3dropout[0… │
│ (Conv1D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_4bn           │ (None, 2054, 512) │      2,048 │ bpnet_4conv[0][0] │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_4activation   │ (None, 2054, 512) │          0 │ bpnet_4bn[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_4crop         │ (None, 2054, 512) │          0 │ bpnet_3dropout[0… │
│ (Cropping1D)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_3 (Add)         │ (None, 2054, 512) │          0 │ bpnet_4activatio… │
│                     │                   │            │ bpnet_4crop[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_4dropout      │ (None, 2054, 512) │          0 │ add_3[0][0]       │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_5conv         │ (None, 1990, 512) │    786,432 │ bpnet_4dropout[0… │
│ (Conv1D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_5bn           │ (None, 1990, 512) │      2,048 │ bpnet_5conv[0][0] │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_5activation   │ (None, 1990, 512) │          0 │ bpnet_5bn[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_5crop         │ (None, 1990, 512) │          0 │ bpnet_4dropout[0… │
│ (Cropping1D)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_4 (Add)         │ (None, 1990, 512) │          0 │ bpnet_5activatio… │
│                     │                   │            │ bpnet_5crop[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_5dropout      │ (None, 1990, 512) │          0 │ add_4[0][0]       │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_6conv         │ (None, 1862, 512) │    786,432 │ bpnet_5dropout[0… │
│ (Conv1D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_6bn           │ (None, 1862, 512) │      2,048 │ bpnet_6conv[0][0] │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_6activation   │ (None, 1862, 512) │          0 │ bpnet_6bn[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_6crop         │ (None, 1862, 512) │          0 │ bpnet_5dropout[0… │
│ (Cropping1D)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_5 (Add)         │ (None, 1862, 512) │          0 │ bpnet_6activatio… │
│                     │                   │            │ bpnet_6crop[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_6dropout      │ (None, 1862, 512) │          0 │ add_5[0][0]       │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_7conv         │ (None, 1606, 512) │    786,432 │ bpnet_6dropout[0… │
│ (Conv1D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_7bn           │ (None, 1606, 512) │      2,048 │ bpnet_7conv[0][0] │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_7activation   │ (None, 1606, 512) │          0 │ bpnet_7bn[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_7crop         │ (None, 1606, 512) │          0 │ bpnet_6dropout[0… │
│ (Cropping1D)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_6 (Add)         │ (None, 1606, 512) │          0 │ bpnet_7activatio… │
│                     │                   │            │ bpnet_7crop[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_7dropout      │ (None, 1606, 512) │          0 │ add_6[0][0]       │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_8conv         │ (None, 1094, 512) │    786,432 │ bpnet_7dropout[0… │
│ (Conv1D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_8bn           │ (None, 1094, 512) │      2,048 │ bpnet_8conv[0][0] │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_8activation   │ (None, 1094, 512) │          0 │ bpnet_8bn[0][0]   │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_8crop         │ (None, 1094, 512) │          0 │ bpnet_7dropout[0… │
│ (Cropping1D)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_7 (Add)         │ (None, 1094, 512) │          0 │ bpnet_8activatio… │
│                     │                   │            │ bpnet_8crop[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bpnet_8dropout      │ (None, 1094, 512) │          0 │ add_7[0][0]       │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_average_poo… │ (None, 512)       │          0 │ bpnet_8dropout[0… │
│ (GlobalAveragePool… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_out (Dense)   │ (None, 49)        │     25,137 │ global_average_p… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 19,017,365 (72.55 MB)

 Trainable params: 6,336,049 (24.17 MB)

 Non-trainable params: 9,216 (36.00 KB)

 Optimizer params: 12,672,100 (48.34 MB)

None
2025-03-21T13:42:18.020233+0000 INFO Loading sequences into memory...

100%|██████████| 58652/58652 [00:01<00:00, 43841.09it/s]

2025-03-21T13:42:19.491507+0000 INFO Loading sequences into memory...

100%|██████████| 7332/7332 [00:00<00:00, 47447.08it/s]

Epoch 4/25

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1742564541.703812  293296 service.cc:152] XLA service 0x153618023570 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1742564541.703840  293296 service.cc:160]   StreamExecutor device (0): NVIDIA A100-SXM4-80GB, Compute Capability 8.0
2025-03-21 13:42:21.869376: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1742564542.502783  293296 cuda_dnn.cc:529] Loaded cuDNN version 90300
2025-03-21 13:42:24.036363: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_7173', 88 bytes spill stores, 88 bytes spill loads

2025-03-21 13:42:24.047917: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_5816', 112 bytes spill stores, 112 bytes spill loads

2025-03-21 13:42:24.052729: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_5816', 4 bytes spill stores, 4 bytes spill loads

2025-03-21 13:42:24.204750: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_5816_0', 368 bytes spill stores, 820 bytes spill loads

2025-03-21 13:42:24.251456: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8116', 32 bytes spill stores, 32 bytes spill loads

2025-03-21 13:42:24.317820: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_5816_0', 396 bytes spill stores, 396 bytes spill loads

2025-03-21 13:42:24.373861: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_5816', 48 bytes spill stores, 48 bytes spill loads

2025-03-21 13:42:24.381048: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_7173', 100 bytes spill stores, 100 bytes spill loads

2025-03-21 13:42:24.436029: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_7173', 872 bytes spill stores, 872 bytes spill loads

2025-03-21 13:42:24.474202: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_5816', 132 bytes spill stores, 132 bytes spill loads

2025-03-21 13:42:24.493865: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_5816', 3400 bytes spill stores, 3400 bytes spill loads

2025-03-21 13:42:24.569984: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_7173', 440 bytes spill stores, 440 bytes spill loads

2025-03-21 13:42:24.618341: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_7173', 756 bytes spill stores, 756 bytes spill loads

2025-03-21 13:42:24.619760: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8116', 152 bytes spill stores, 152 bytes spill loads

2025-03-21 13:42:24.642951: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_7173', 580 bytes spill stores, 580 bytes spill loads

2025-03-21 13:42:24.729370: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_7173', 140 bytes spill stores, 140 bytes spill loads

2025-03-21 13:42:24.780635: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_7173', 880 bytes spill stores, 880 bytes spill loads

2025-03-21 13:42:24.834388: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8116', 524 bytes spill stores, 524 bytes spill loads

2025-03-21 13:42:24.944840: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8116_0', 164 bytes spill stores, 164 bytes spill loads

2025-03-21 13:42:24.953974: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8116', 4 bytes spill stores, 4 bytes spill loads

2025-03-21 13:42:24.965152: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_7173', 56 bytes spill stores, 56 bytes spill loads

2025-03-21 13:42:25.088888: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8116', 248 bytes spill stores, 248 bytes spill loads

2025-03-21 13:42:28.648256: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.18 = (f32[512,512,1,1055]{3,2,1,0}, u8[0]{0}) custom-call(f32[512,512,1,1057]{3,2,1,0} %bitcast.32301, f32[512,512,1,3]{3,2,1,0} %bitcast.34655), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_1conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:30.554719: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 2.90653155s
Trying algorithm eng0{} for conv %cudnn-conv.18 = (f32[512,512,1,1055]{3,2,1,0}, u8[0]{0}) custom-call(f32[512,512,1,1057]{3,2,1,0} %bitcast.32301, f32[512,512,1,3]{3,2,1,0} %bitcast.34655), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_1conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:33.568455: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.19 = (f32[1024,512,1,526]{3,2,1,0}, u8[0]{0}) custom-call(f32[1024,512,1,528]{3,2,1,0} %bitcast.32383, f32[512,512,1,3]{3,2,1,0} %bitcast.34545), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_2conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:35.417832: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 2.849411839s
Trying algorithm eng0{} for conv %cudnn-conv.19 = (f32[1024,512,1,526]{3,2,1,0}, u8[0]{0}) custom-call(f32[1024,512,1,528]{3,2,1,0} %bitcast.32383, f32[512,512,1,3]{3,2,1,0} %bitcast.34545), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_2conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:38.399183: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.20 = (f32[2048,512,1,261]{3,2,1,0}, u8[0]{0}) custom-call(f32[2048,512,1,263]{3,2,1,0} %bitcast.32464, f32[512,512,1,3]{3,2,1,0} %bitcast.34434), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_3conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:40.296144: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 2.897020248s
Trying algorithm eng0{} for conv %cudnn-conv.20 = (f32[2048,512,1,261]{3,2,1,0}, u8[0]{0}) custom-call(f32[2048,512,1,263]{3,2,1,0} %bitcast.32464, f32[512,512,1,3]{3,2,1,0} %bitcast.34434), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_3conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:43.270566: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.21 = (f32[4096,512,1,129]{3,2,1,0}, u8[0]{0}) custom-call(f32[4096,512,1,131]{3,2,1,0} %bitcast.32545, f32[512,512,1,3]{3,2,1,0} %bitcast.34323), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_4conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:45.383102: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 3.112574177s
Trying algorithm eng0{} for conv %cudnn-conv.21 = (f32[4096,512,1,129]{3,2,1,0}, u8[0]{0}) custom-call(f32[4096,512,1,131]{3,2,1,0} %bitcast.32545, f32[512,512,1,3]{3,2,1,0} %bitcast.34323), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_4conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:48.344568: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.22 = (f32[8192,512,1,63]{3,2,1,0}, u8[0]{0}) custom-call(f32[8192,512,1,65]{3,2,1,0} %bitcast.32626, f32[512,512,1,3]{3,2,1,0} %bitcast.34212), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_5conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:50.328788: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 2.98428247s
Trying algorithm eng0{} for conv %cudnn-conv.22 = (f32[8192,512,1,63]{3,2,1,0}, u8[0]{0}) custom-call(f32[8192,512,1,65]{3,2,1,0} %bitcast.32626, f32[512,512,1,3]{3,2,1,0} %bitcast.34212), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_5conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:52.999147: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.23 = (f32[16384,512,1,30]{3,2,1,0}, u8[0]{0}) custom-call(f32[16384,512,1,32]{3,2,1,0} %bitcast.32707, f32[512,512,1,3]{3,2,1,0} %bitcast.34101), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_6conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:55.122088: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 3.122993515s
Trying algorithm eng0{} for conv %cudnn-conv.23 = (f32[16384,512,1,30]{3,2,1,0}, u8[0]{0}) custom-call(f32[16384,512,1,32]{3,2,1,0} %bitcast.32707, f32[512,512,1,3]{3,2,1,0} %bitcast.34101), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_6conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:56.858900: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.24 = (f32[32768,512,1,13]{3,2,1,0}, u8[0]{0}) custom-call(f32[32768,512,1,15]{3,2,1,0} %bitcast.32788, f32[512,512,1,3]{3,2,1,0} %bitcast.33990), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_7conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:42:58.680564: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 2.821694598s
Trying algorithm eng0{} for conv %cudnn-conv.24 = (f32[32768,512,1,13]{3,2,1,0}, u8[0]{0}) custom-call(f32[32768,512,1,15]{3,2,1,0} %bitcast.32788, f32[512,512,1,3]{3,2,1,0} %bitcast.33990), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_7conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:43:01.681382: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.25 = (f32[65536,512,1,5]{3,2,1,0}, u8[0]{0}) custom-call(f32[65536,512,1,7]{3,2,1,0} %bitcast.32869, f32[512,512,1,3]{3,2,1,0} %bitcast.33879), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_8conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:43:02.649675: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 1.968328428s
Trying algorithm eng0{} for conv %cudnn-conv.25 = (f32[65536,512,1,5]{3,2,1,0}, u8[0]{0}) custom-call(f32[65536,512,1,7]{3,2,1,0} %bitcast.32869, f32[512,512,1,3]{3,2,1,0} %bitcast.33879), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_8conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...

458/459 ━━━━━━━━━━━━━━━━━━━━ 0s 438ms/step - concordance_correlation_coefficient: 0.0010 - cosine_similarity: 0.5494 - loss: 1.6042 - mean_absolute_error: 0.0529 - mean_squared_error: 63.2612 - pearson_correlation: 0.0031 - pearson_correlation_log: 0.0482 - zero_penalty_metric: 678.8425

2025-03-21 13:47:43.416956: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_7173', 192 bytes spill stores, 192 bytes spill loads

2025-03-21 13:47:43.431735: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_5816', 168 bytes spill stores, 168 bytes spill loads

2025-03-21 13:47:43.478691: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_5816', 24 bytes spill stores, 24 bytes spill loads

2025-03-21 13:47:43.516453: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_5816', 24 bytes spill stores, 24 bytes spill loads

2025-03-21 13:47:43.853789: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_5816', 4276 bytes spill stores, 4252 bytes spill loads

2025-03-21 13:47:43.940306: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8116', 92 bytes spill stores, 92 bytes spill loads

2025-03-21 13:47:44.007635: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8116', 520 bytes spill stores, 520 bytes spill loads

2025-03-21 13:47:44.021759: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_7173', 948 bytes spill stores, 948 bytes spill loads

2025-03-21 13:47:44.084020: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8116', 56 bytes spill stores, 56 bytes spill loads

2025-03-21 13:47:53.854489: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng25{k2=0,k3=0} for conv %cudnn-conv-bw-input.8 = (f32[14336,512,1,7]{3,2,1,0}, u8[0]{0}) custom-call(f32[14336,512,1,5]{3,2,1,0} %bitcast.33878, f32[512,512,1,3]{3,2,1,0} %bitcast.33880), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convBackwardInput", metadata={op_type="Conv2DBackpropInput" op_name="gradient_tape/functional_1/bpnet_8conv_1/convolution/Conv2DBackpropInput" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:47:54.014790: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 1.160361653s
Trying algorithm eng25{k2=0,k3=0} for conv %cudnn-conv-bw-input.8 = (f32[14336,512,1,7]{3,2,1,0}, u8[0]{0}) custom-call(f32[14336,512,1,5]{3,2,1,0} %bitcast.33878, f32[512,512,1,3]{3,2,1,0} %bitcast.33880), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convBackwardInput", metadata={op_type="Conv2DBackpropInput" op_name="gradient_tape/functional_1/bpnet_8conv_1/convolution/Conv2DBackpropInput" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...

459/459 ━━━━━━━━━━━━━━━━━━━━ 0s 519ms/step - concordance_correlation_coefficient: 0.0010 - cosine_similarity: 0.5494 - loss: 1.6038 - mean_absolute_error: 0.0529 - mean_squared_error: 63.2092 - pearson_correlation: 0.0031 - pearson_correlation_log: 0.0482 - zero_penalty_metric: 677.6118

2025-03-21 13:48:25.318048: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_684', 24 bytes spill stores, 24 bytes spill loads

2025-03-21 13:48:25.402964: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_684', 168 bytes spill stores, 168 bytes spill loads

2025-03-21 13:48:25.409392: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_684', 4 bytes spill stores, 4 bytes spill loads

2025-03-21 13:48:25.450502: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_684', 40 bytes spill stores, 40 bytes spill loads

2025-03-21 13:48:25.527119: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_684_0', 524 bytes spill stores, 524 bytes spill loads

2025-03-21 13:48:25.752779: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_684', 172 bytes spill stores, 172 bytes spill loads

2025-03-21 13:48:25.819123: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_684', 784 bytes spill stores, 784 bytes spill loads

2025-03-21 13:48:25.823898: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_684', 4276 bytes spill stores, 4252 bytes spill loads

2025-03-21 13:48:28.325447: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.10 = (f32[328,512,1,1055]{3,2,1,0}, u8[0]{0}) custom-call(f32[328,512,1,1057]{3,2,1,0} %bitcast.2967, f32[512,512,1,3]{3,2,1,0} %bitcast.2972), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_1conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:29.187916: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 1.862520983s
Trying algorithm eng0{} for conv %cudnn-conv.10 = (f32[328,512,1,1055]{3,2,1,0}, u8[0]{0}) custom-call(f32[328,512,1,1057]{3,2,1,0} %bitcast.2967, f32[512,512,1,3]{3,2,1,0} %bitcast.2972), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_1conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:31.495914: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.11 = (f32[656,512,1,526]{3,2,1,0}, u8[0]{0}) custom-call(f32[656,512,1,528]{3,2,1,0} %bitcast.3017, f32[512,512,1,3]{3,2,1,0} %bitcast.3022), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_2conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:32.321801: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 1.825956935s
Trying algorithm eng0{} for conv %cudnn-conv.11 = (f32[656,512,1,526]{3,2,1,0}, u8[0]{0}) custom-call(f32[656,512,1,528]{3,2,1,0} %bitcast.3017, f32[512,512,1,3]{3,2,1,0} %bitcast.3022), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_2conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:34.602451: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.12 = (f32[1312,512,1,261]{3,2,1,0}, u8[0]{0}) custom-call(f32[1312,512,1,263]{3,2,1,0} %bitcast.3068, f32[512,512,1,3]{3,2,1,0} %bitcast.3073), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_3conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:35.458984: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 1.85656426s
Trying algorithm eng0{} for conv %cudnn-conv.12 = (f32[1312,512,1,261]{3,2,1,0}, u8[0]{0}) custom-call(f32[1312,512,1,263]{3,2,1,0} %bitcast.3068, f32[512,512,1,3]{3,2,1,0} %bitcast.3073), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_3conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:37.734012: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.13 = (f32[2624,512,1,129]{3,2,1,0}, u8[0]{0}) custom-call(f32[2624,512,1,131]{3,2,1,0} %bitcast.3119, f32[512,512,1,3]{3,2,1,0} %bitcast.3124), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_4conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:38.728266: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 1.994308336s
Trying algorithm eng0{} for conv %cudnn-conv.13 = (f32[2624,512,1,129]{3,2,1,0}, u8[0]{0}) custom-call(f32[2624,512,1,131]{3,2,1,0} %bitcast.3119, f32[512,512,1,3]{3,2,1,0} %bitcast.3124), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_4conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:40.995349: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.14 = (f32[5248,512,1,63]{3,2,1,0}, u8[0]{0}) custom-call(f32[5248,512,1,65]{3,2,1,0} %bitcast.3170, f32[512,512,1,3]{3,2,1,0} %bitcast.3175), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_5conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:41.907829: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 1.912539885s
Trying algorithm eng0{} for conv %cudnn-conv.14 = (f32[5248,512,1,63]{3,2,1,0}, u8[0]{0}) custom-call(f32[5248,512,1,65]{3,2,1,0} %bitcast.3170, f32[512,512,1,3]{3,2,1,0} %bitcast.3175), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_5conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:44.090266: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.15 = (f32[10496,512,1,30]{3,2,1,0}, u8[0]{0}) custom-call(f32[10496,512,1,32]{3,2,1,0} %bitcast.3221, f32[512,512,1,3]{3,2,1,0} %bitcast.3226), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_6conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:45.089142: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 1.998943997s
Trying algorithm eng0{} for conv %cudnn-conv.15 = (f32[10496,512,1,30]{3,2,1,0}, u8[0]{0}) custom-call(f32[10496,512,1,32]{3,2,1,0} %bitcast.3221, f32[512,512,1,3]{3,2,1,0} %bitcast.3226), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_6conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:46.712421: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.16 = (f32[20992,512,1,13]{3,2,1,0}, u8[0]{0}) custom-call(f32[20992,512,1,15]{3,2,1,0} %bitcast.3272, f32[512,512,1,3]{3,2,1,0} %bitcast.3277), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_7conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:47.520895: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 1.808547308s
Trying algorithm eng0{} for conv %cudnn-conv.16 = (f32[20992,512,1,13]{3,2,1,0}, u8[0]{0}) custom-call(f32[20992,512,1,15]{3,2,1,0} %bitcast.3272, f32[512,512,1,3]{3,2,1,0} %bitcast.3277), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_7conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:49.496951: E external/local_xla/xla/service/slow_operation_alarm.cc:73] Trying algorithm eng0{} for conv %cudnn-conv.17 = (f32[41984,512,1,5]{3,2,1,0}, u8[0]{0}) custom-call(f32[41984,512,1,7]{3,2,1,0} %bitcast.3323, f32[512,512,1,3]{3,2,1,0} %bitcast.3328), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_8conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...
2025-03-21 13:48:49.757532: E external/local_xla/xla/service/slow_operation_alarm.cc:140] The operation took 1.260638931s
Trying algorithm eng0{} for conv %cudnn-conv.17 = (f32[41984,512,1,5]{3,2,1,0}, u8[0]{0}) custom-call(f32[41984,512,1,7]{3,2,1,0} %bitcast.3323, f32[512,512,1,3]{3,2,1,0} %bitcast.3328), window={size=1x3}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convForward", metadata={op_type="Conv2D" op_name="functional_1/bpnet_8conv_1/convolution" source_file="/home/bt392/miniconda3/envs/crested/lib/python3.11/site-packages/tensorflow/python/framework/ops.py" source_line=1200}, backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"conv_result_scale":1,"activation_mode":"kNone","side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false} is taking a while...

459/459 ━━━━━━━━━━━━━━━━━━━━ 392s 591ms/step - concordance_correlation_coefficient: 0.0010 - cosine_similarity: 0.5495 - loss: 1.6033 - mean_absolute_error: 0.0529 - mean_squared_error: 63.1575 - pearson_correlation: 0.0031 - pearson_correlation_log: 0.0481 - zero_penalty_metric: 676.3865 - val_concordance_correlation_coefficient: 4.0327e-09 - val_cosine_similarity: 0.5447 - val_loss: 1.3175 - val_mean_absolute_error: 0.0165 - val_mean_squared_error: 0.6008 - val_pearson_correlation: 0.0187 - val_pearson_correlation_log: 0.1952 - val_zero_penalty_metric: 0.1092 - learning_rate: 0.0010
Epoch 5/25
459/459 ━━━━━━━━━━━━━━━━━━━━ 204s 444ms/step - concordance_correlation_coefficient: 4.3632e-09 - cosine_similarity: 0.6136 - loss: 1.2862 - mean_absolute_error: 0.0357 - mean_squared_error: 39.5479 - pearson_correlation: 0.0418 - pearson_correlation_log: 0.3273 - zero_penalty_metric: 0.0979 - val_concordance_correlation_coefficient: 2.3310e-09 - val_cosine_similarity: 0.5145 - val_loss: 1.3289 - val_mean_absolute_error: 0.0165 - val_mean_squared_error: 0.6008 - val_pearson_correlation: 0.0212 - val_pearson_correlation_log: 0.2777 - val_zero_penalty_metric: 0.1272 - learning_rate: 0.0010
Epoch 6/25
459/459 ━━━━━━━━━━━━━━━━━━━━ 204s 444ms/step - concordance_correlation_coefficient: 2.2271e-09 - cosine_similarity: 0.6180 - loss: 1.2990 - mean_absolute_error: 0.0347 - mean_squared_error: 27.0773 - pearson_correlation: 0.0638 - pearson_correlation_log: 0.3794 - zero_penalty_metric: 0.1094 - val_concordance_correlation_coefficient: 4.4640e-09 - val_cosine_similarity: 0.5352 - val_loss: 1.2910 - val_mean_absolute_error: 0.0165 - val_mean_squared_error: 0.6008 - val_pearson_correlation: 0.0320 - val_pearson_correlation_log: 0.3074 - val_zero_penalty_metric: 0.1326 - learning_rate: 0.0010
Epoch 7/25
459/459 ━━━━━━━━━━━━━━━━━━━━ 204s 444ms/step - concordance_correlation_coefficient: 8.2112e-09 - cosine_similarity: 0.6218 - loss: 1.2949 - mean_absolute_error: 0.0372 - mean_squared_error: 29.1444 - pearson_correlation: 0.0980 - pearson_correlation_log: 0.2702 - zero_penalty_metric: 0.1226 - val_concordance_correlation_coefficient: 1.7703e-08 - val_cosine_similarity: 0.4606 - val_loss: 1.3511 - val_mean_absolute_error: 0.0165 - val_mean_squared_error: 0.6008 - val_pearson_correlation: 0.0381 - val_pearson_correlation_log: 0.2270 - val_zero_penalty_metric: 0.1995 - learning_rate: 0.0010
Epoch 8/25
459/459 ━━━━━━━━━━━━━━━━━━━━ 0s 437ms/step - concordance_correlation_coefficient: 1.5683e-04 - cosine_similarity: 0.6231 - loss: 1.2462 - mean_absolute_error: 0.0506 - mean_squared_error: 58.9097 - pearson_correlation: 0.0607 - pearson_correlation_log: 0.1547 - zero_penalty_metric: 95.2969

In [ ]:
trainer

In [ ]:
trainer.test()

In [47]:
crested.pp.change_regions_width(
    adata, 600
)  # change the adata width of the regions to 2114bp

In [48]:
#crested.pp.normalize_peaks(adata)

In [49]:
# %matplotlib inline
# crested.pl.bar.normalization_weights(adata, title="Normalization Weights per Cell Type")

In [50]:
# This one is a bit extreme, so either something should change with the inputs or just no normalisation

In [51]:
# Set the genome
genome = crested.Genome(
    "/home/bt392/rds/rds-bg200-hphi-gottgens/references/10x/refdata-cellranger-arc-mm10-2020-A-2.0.0/fasta/genome.fa", 
    "/home/bt392/rds/rds-bg200-hphi-gottgens/users/bt392/10_Eomes_invitro_gut/results/atac/chrombpnet/mm10.chrom.sizes"
)
crested.register_genome(
    genome
)  # Register the genome so that it can be used by the package

2025-03-21T14:13:21.050333+0000 INFO Genome genome registered.

In [52]:
adata.obs

                      celltype
celltype
Baso                      Baso
BasoP                    BasoP
cDC1                      cDC1
cDC2a                    cDC2a
cDC2b                    cDC2b
cDC3                      cDC3
Eos                        Eos
Ery1                      Ery1
Ery2                      Ery2
Ery3                      Ery3
Ery4                      Ery4
GMP                        GMP
Immature B          Immature B
LT HSC                  LT HSC
LyDCP                    LyDCP
LyP                        LyP
MEP                        MEP
MKP                        MKP
MMP1                      MMP1
MMP2                      MMP2
MMP3                      MMP3
MoDCP                    MoDCP
Mono Ly6c-          Mono Ly6c-
Mono Ly6c+          Mono Ly6c+
Mono1                    Mono1
Mono2                    Mono2
MPP A                    MPP A
MPP B                    MPP B
MPP C                    MPP C
Neut1                    Neut1
Neut2                    Neut2
Neut3                    Neut3
NeutP                    NeutP
NeutP2                  NeutP2
NK                          NK
NKT                        NKT
pDC                        pDC
Pre B cyc            Pre B cyc
Pre cDC1              Pre cDC1
Pre cDC2              Pre cDC2
PreB                      PreB
Pro B                    Pro B
ST HSC                  ST HSC
T CD4                    T CD4
T CD4 memory      T CD4 memory
T CD8                    T CD8
T GD                      T GD
T reg                    T reg
Transitional B  Transitional B

In [54]:
adata = adata[:, [1,2]]

In [56]:
datamodule = crested.tl.data.AnnDataModule(
    adata,
    batch_size=256,  # lower this if you encounter OOM errors
    max_stochastic_shift=3,  # optional data augmentation to slightly reduce overfitting
    always_reverse_complement=True,  # default True. Will double the effective size of the training dataset.
)

In [57]:
crested.tl.zoo.chrombpnet

<function crested.tl.zoo._chrombpnet.chrombpnet(seq_len: int, num_classes: int, first_conv_filters: int = 512, first_conv_filter_size: int = 5, first_conv_pool_size: int = 0, first_conv_activation: str = 'gelu', first_conv_l2: float = 1e-05, first_conv_dropout: float = 0.1, n_dil_layers: int = 8, num_filters: int = 512, filter_size: int = 3, activation: str = 'relu', output_activation: str = 'softplus', l2: float = 1e-05, dropout: float = 0.1, batch_norm: bool = True, dense_bias: bool = True) -> keras.src.models.model.Model>

In [58]:
# Their default model is slightly different from the original bpnet
# mainly the width of the first convolutional filter is way smaller
model_architecture = crested.tl.zoo.simple_convnet(seq_len=600, num_classes=2)

In [59]:
# Load the default configuration for training a topic classication model
from crested.tl import default_configs, TaskConfig

config = default_configs("peak_regression")
print(config)

# If you want to change some small parameters to an existing config, you can do it like this
# For example, the default learning rate is 0.001, but you can change it to 0.0001
# config.optimizer.learning_rate = 0.0001

TaskConfig(optimizer=<keras.src.optimizers.adam.Adam object at 0x1507762a2890>, loss=<crested.tl.losses._cosinemse_log.CosineMSELogLoss object at 0x1507f24f1f50>, metrics=[<MeanAbsoluteError name=mean_absolute_error>, <MeanSquaredError name=mean_squared_error>, <CosineSimilarity name=cosine_similarity>, <PearsonCorrelation name=pearson_correlation>, <ConcordanceCorrelationCoefficient name=concordance_correlation_coefficient>, <PearsonCorrelationLog name=pearson_correlation_log>, <ZeroPenaltyMetric name=zero_penalty_metric>])

In [62]:
# setup the trainer
trainer = crested.tl.Crested(
    data=datamodule,
    model=model_architecture,
    config=config,
    project_name="/rds/project/rds-SDzz0CATGms/users/bt392/15_Kat_Atlas/results/crested",  # change to your liking
    run_name="trial4",  # change to your liking
    logger=None,  # or 'wandb', 'tensorboard'
)

In [63]:
# train the model
trainer.fit(epochs=25, early_stopping_patience=4)

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ sequence (InputLayer)           │ (None, 600, 4)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_12 (Conv1D)              │ (None, 588, 192)       │        10,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_16          │ (None, 588, 192)       │           768 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_16 (Activation)      │ (None, 588, 192)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_12 (MaxPooling1D) │ (None, 73, 192)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_16 (Dropout)            │ (None, 73, 192)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_13 (Conv1D)              │ (None, 67, 256)        │       344,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_17          │ (None, 67, 256)        │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_17 (Activation)      │ (None, 67, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_13 (MaxPooling1D) │ (None, 33, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_17 (Dropout)            │ (None, 33, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_14 (Conv1D)              │ (None, 27, 512)        │       918,016 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_18          │ (None, 27, 512)        │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_18 (Activation)      │ (None, 27, 512)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_14 (MaxPooling1D) │ (None, 13, 512)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_18 (Dropout)            │ (None, 13, 512)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 6656)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 256)            │     1,704,192 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_19          │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_19 (Activation)      │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_19 (Dropout)            │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ denseblock_dense (Dense)        │ (None, 8)              │         2,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ denseblock_batchnorm            │ (None, 8)              │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ denseblock_activation           │ (None, 8)              │             0 │
│ (Activation)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ denseblock_dropout (Dropout)    │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_out (Dense)               │ (None, 2)              │            18 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,983,674 (11.38 MB)

 Trainable params: 2,981,226 (11.37 MB)

 Non-trainable params: 2,448 (9.56 KB)

None
2025-03-21T14:14:17.574706+0000 INFO Loading sequences into memory...

100%|██████████| 2/2 [00:00<00:00, 13189.64it/s]

IndexError: list index out of range